"use client";

import { useState } from "react";
import { Banknote, CalendarDays, Calculator } from "lucide-react";

type Calculation = { workDays: number; totalCost: number; };
const parseLocalDate = (value: string) => new Date(`${value}T00:00:00`);

export default function CostCalculatorTool() {
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [result, setResult] = useState<Calculation | null>(null);
  const [error, setError] = useState("");
  const calculate = () => { if (!startDate || !endDate) { setError("시작일과 종료일을 모두 선택해 주세요."); setResult(null); return; } const start = parseLocalDate(startDate); const end = parseLocalDate(endDate); if (start > end) { setError("종료일은 시작일보다 빠를 수 없습니다."); setResult(null); return; } let workDays = 0; const cursor = new Date(start); while (cursor <= end) { const weekday = cursor.getDay(); if (weekday !== 0 && weekday !== 6) workDays += 1; cursor.setDate(cursor.getDate() + 1); } const totalCost = workDays === 0 ? 0 : workDays <= 10 ? 100000 : 100000 + (workDays - 10) * 10000; setResult({ workDays, totalCost }); setError(""); };
  return <section className="mx-auto w-full max-w-2xl px-4 py-10 sm:px-6"><div className="border-b border-gray-200 pb-7 dark:border-dark-700"><p className="text-sm font-semibold text-primary-600">COST</p><h1 className="mt-3 text-3xl font-bold text-gray-950 dark:text-white">공사비 계산기</h1><p className="mt-3 text-sm leading-6 text-gray-600 dark:text-dark-300">주말을 제외한 공사 기간과 비용을 계산합니다.</p></div><div className="mt-7 border border-gray-200 bg-white p-5 dark:border-dark-700 dark:bg-dark-900 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold text-gray-800 dark:text-dark-100">시작 날짜<input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} className="h-11 border border-gray-300 bg-white px-3 text-gray-950 outline-none focus:border-gray-950 dark:border-dark-600 dark:bg-dark-950 dark:text-white dark:focus:border-white" /></label><label className="grid gap-2 text-sm font-semibold text-gray-800 dark:text-dark-100">종료 날짜<input type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} className="h-11 border border-gray-300 bg-white px-3 text-gray-950 outline-none focus:border-gray-950 dark:border-dark-600 dark:bg-dark-950 dark:text-white dark:focus:border-white" /></label></div><button type="button" onClick={calculate} className="mt-6 inline-flex h-11 w-full items-center justify-center gap-2 bg-gray-950 px-5 text-sm font-semibold text-white hover:bg-gray-800 dark:bg-white dark:text-gray-950"><Calculator className="h-4 w-4" /> 계산하기</button>{error && <p className="mt-4 text-sm font-medium text-red-600" role="alert">{error}</p>}</div>{result && <div className="mt-5 grid gap-4 border border-gray-200 bg-gray-50 p-5 dark:border-dark-700 dark:bg-dark-900 sm:grid-cols-2 sm:p-7"><div><div className="flex items-center gap-2 text-sm font-medium text-gray-500 dark:text-dark-300"><CalendarDays className="h-4 w-4" /> 총 공사 기간</div><p className="mt-3 text-3xl font-bold text-gray-950 dark:text-white">{result.workDays.toLocaleString()}일</p><p className="mt-2 text-sm text-gray-500 dark:text-dark-300">주말 제외</p></div><div><div className="flex items-center gap-2 text-sm font-medium text-gray-500 dark:text-dark-300"><Banknote className="h-4 w-4" /> 최종 산출 금액</div><p className="mt-3 text-3xl font-bold text-primary-700 dark:text-primary-300">{result.totalCost.toLocaleString()}원</p><p className="mt-2 text-sm text-gray-500 dark:text-dark-300">10일 이내 100,000원, 이후 1일당 10,000원 추가</p></div></div>}</section>;
}
