import fs from "fs";
import path from "path";

const rootDir = process.cwd();
const coreSchemaPath = path.join(rootDir, "src", "core", "prisma", "schema.prisma");
const fragmentSources = [
  {
    name: "Extension",
    singleSchemaPath: path.join(rootDir, "src", "extensions", "prisma", "schema.prisma"),
    schemaDir: path.join(rootDir, "src", "extensions", "prisma", "schema"),
  },
];
const outputDir = path.join(rootDir, "prisma");
const outputPath = path.join(outputDir, "schema.prisma");
const legacyOutputSeedPath = path.join(outputDir, "seed.js");
const legacyOutputMigrationsPath = path.join(outputDir, "migrations");

const readIfExists = (filePath) => {
  if (!fs.existsSync(filePath)) return null;
  return fs.readFileSync(filePath, "utf8").trim();
};

const readSchemaFragments = () => {
  const fragments = [];

  for (const source of fragmentSources) {
    const singleSchema = readIfExists(source.singleSchemaPath);

    if (singleSchema) {
      fragments.push({
        source: source.name,
        label: path.relative(rootDir, source.singleSchemaPath),
        content: singleSchema,
      });
    }

    if (fs.existsSync(source.schemaDir)) {
      const files = fs
        .readdirSync(source.schemaDir)
        .filter((fileName) => fileName.endsWith(".prisma"))
        .sort((a, b) => a.localeCompare(b));

      for (const fileName of files) {
        const filePath = path.join(source.schemaDir, fileName);
        const content = readIfExists(filePath);
        if (!content) continue;

        fragments.push({
          source: source.name,
          label: path.relative(rootDir, filePath),
          content,
        });
      }
    }
  }

  return fragments;
};

const coreSchema = readIfExists(coreSchemaPath);

if (!coreSchema) {
  console.error(`Core Prisma schema not found: ${path.relative(rootDir, coreSchemaPath)}`);
  process.exit(1);
}

const schemaFragments = readSchemaFragments();
const generatedSchema = [
  "// This file is generated by scripts/sync-prisma.mjs.",
  "// Edit src/core/prisma/schema.prisma for core schema changes.",
  "// Edit src/extensions/prisma/schema/*.prisma for install-specific extension schema changes.",
  "",
  coreSchema,
  ...schemaFragments.flatMap((fragment) => [
    "",
    `// ${fragment.source} schema: ${fragment.label}`,
    fragment.content,
  ]),
  "",
].join("\n");

fs.mkdirSync(outputDir, { recursive: true });
fs.rmSync(legacyOutputSeedPath, { force: true });
fs.rmSync(legacyOutputMigrationsPath, { recursive: true, force: true });
fs.writeFileSync(outputPath, generatedSchema);

console.log(`Synced Prisma schema to ${path.relative(rootDir, outputPath)}`);
if (schemaFragments.length > 0) {
  console.log(`Included ${schemaFragments.length} schema fragment(s).`);
}
